#!/bin/bash

implemented="0,0 0,1 0,2 3,0 3,1 3,2"
size="8K"
dire="Y"

if [ ! -z "$1" ]; then
	size="$1"
fi

if [ ! -z "$2" ] && [ "$2" == "N" ]; then
	dire="N"
fi

./sendpar --value 100 --size "$size" --direction="$dire"

sudo dmesg --clear

./sendcmd "$implemented"

sleep 2
dmesg
