#!/bin/bash

if [ ! -z "$1" ] && [ "$1" == "Y" ]; then
	./sendpar --value 100 --size 128 --amount 36100 --async=Y --verbose 1
else
	./sendpar --value 100 --size 128 --amount 36100 --async=N --verbose 1
fi

sudo dmesg --clear

./sendtest 3

sleep 1
dmesg
