#!/bin/bash

./dotestdev

if [ ! -z $1 ] && [ $1 == "Y" ]; then
	./sendpar --value 100 --size 128 --amount 36100 --async
else
	./sendpar --value 100 --size 128 --amount 36100
fi

sudo dmesg --clear

./sendtest 3

echo

sleep 1
dmesg
