#!/bin/bash

./dotestdev

if [ ! -z "$1" ] && [ "$1" == "Y" ]; then
	./sendpar --value 100 --size 32 --amount 40960 --verbose 1 --async Y
else
	./sendpar --value 100 --size 32 --amount 40960 --verbose 1 --async N
fi

sudo dmesg --clear
./sendtest 3

echo

sleep 1
dmesg
