#!/bin/bash

size="8K"
async="Y"

if [ ! -z "$1" ] && [ "$1" == "N" ]; then
	async="N"
fi

if [ ! -z "$2" ]; then
	size="$2"
fi

./sendpar --value 100 --size "$size" --async="$async" --verbose 1

sudo dmesg --clear

./sendtest 3 0

sleep 1
dmesg
