#!/bin/bash

size="256K"
periods=10
limit=""
paused=""
ini_t=0

if [ ! -z "$1" ]; then
	size="$1"
fi

if [ ! -z "$2" ]; then
	periods="$2"
fi

if [ ! -z "$3" ]; then
	limit="$3"
fi

if [ ! -c /dev/dmatest ]; then
	./dotestdev && clear
fi

max_chann=$(( $(sudo cat /sys/kernel/debug/dmatest/max_chann) - 1 ))

print_res() {
	sleep 0.5
	for i in `seq 0 $max_chann`; do dmesg | grep --color=always "$i >>"; echo ; done
}

print_status() {
	
	irqs=$(cat /proc/interrupts | grep s805_dmaengine_irq | awk '{print $2}')
	to=$(cat /proc/interrupts | grep s805_dmaengine_to_irq | awk '{print $2}')
	timed_out=$([ -z $to ] && echo -n "NO_TIMEOUT" || echo -n $to)
	cycles=$(( $irqs / $periods ))
	elapsed=$(date -u -d "0 $SECONDS seconds - $ini_t seconds" +'%-Hh %-Mm %-Ss')
	
	echo -en "\r\e[KCYCLES: $cycles, (IRQs: $irqs / TIMED_OUT: $timed_out) | elapsed: $elapsed $paused"
}

pause_resume() {
	
	if [ ! -z $paused ]; then
		./sendcmd 11
		paused=""
	else
		./sendcmd 10
		paused="~PAUSED~"
	fi
	
	echo -ne "\e[1A"
}

trap './sendcmd 9 && echo && print_res && cat /proc/irq/68/spurious | grep -v "count" && exit' SIGINT SIGTERM
trap 'pause_resume' SIGQUIT

sudo dmesg --clear && ./sendpar -p "$periods" -s "$size" -v 0 && ./sendcmd 1 1,0 1,1 1,2 1,3

ini_t=$SECONDS
if [ ! -z $limit ]; then
	for i in `seq 0 $limit`; do
		print_status
		sleep 1
	done
	
	./sendcmd 9 && echo && print_res
	
	cat /proc/irq/68/spurious | grep -v "count"
else
	while true; do
		print_status
        sleep 0.5
    done
fi
