#!/bin/bash

device="dmatest"

#echo -n "initcall_debug: " && cat /sys/module/kernel/parameters/initcall_debug

if [ -z $1 ]; then
	chann=4
else
	chann="$1"
fi

if [ -c /dev/${device} ]; then
	sudo rmmod ${device}
	sudo rm -rf /dev/${device}
fi

#Debug para module_init.
#echo 'Y' | sudo tee /sys/module/kernel/parameters/initcall_debug

make clean && make -j4
sudo dmesg --clear
sudo insmod ${device}.ko max_chann=${chann}
dmesg

sudo mknod /dev/${device} c $(sudo cat /sys/kernel/debug/${device}/major) 1

sudo journalctl --flush
