#!/bin/bash

if [ ! -c /dev/dmatest ]; then
	./dotestdev
fi

implemented="7 0 2 0,0 0,1 0,2 2,0 2,1 2,2 2,3 3 3,0 4 5 6" #1,0 1,1 1,2 1,3 7 2,0
size="256K"
dire="Y"
periods=15
max_chann=$(( $(sudo cat /sys/kernel/debug/dmatest/max_chann) - 1 ))

if [ ! -z "$1" ]; then
	size="$1"
fi

if [ ! -z "$2" ] && [ "$2" == "N" ]; then
	dire="N"
fi

if [ ! -z "$3" ]; then
	periods="$3"
fi


./sendpar --value 100 --size "$size" --direction="$dire" --periods "$periods" #-b

sudo dmesg --clear

./sendcmd "$implemented"

sleep 1

#issue jobs
#./sendcmd 8

sleep 5

# stop cyclic transfers
#./sendcmd 9

for i in `seq 0 $max_chann`; do dmesg | grep --color=always "$i >>"; echo ; done

echo "TIMED_OUT: $(cat /proc/interrupts | grep s805_dmaengine_to_irq | awk '{print $2}')"
