#!/bin/bash

if [ ! -c /dev/dmatest ]; then
	./dotestdev
fi

implemented="7 0 2 0,0 0,1 0,2 2,0 2,1 2,2 2,3 4 5 6"
size="32K"
dire="Y"
max_chann=$(( $(sudo cat /sys/kernel/debug/dmatest/max_chann) - 1 ))

if [ ! -z "$1" ]; then
	size="$1"
fi

if [ ! -z "$2" ] && [ "$2" == "N" ]; then
	dire="N"
fi

./sendpar --value 100 --size "$size" --direction="$dire"

sudo dmesg --clear

./sendcmd "$implemented"

sleep 2

for i in `seq 0 $max_chann`; do dmesg | grep --color=always "$i >>"; echo ; done
