#!/bin/bash

if [ ! -c /dev/dmatest ]; then
	./dotestdev
fi

# read the options
TEMP=`getopt -o n:s:p:v:a::d::b::m:: --long value:,size:,periods:,verbose:,async::,direction::,batch::,mode2d:: -n 'sendpar' -- "$@"`
eval set -- "$TEMP"

while true ; do
	#echo "parsing: ($1,$2)"
    case "$1" in
		-n | --value)
			value="$2"; shift 2 ;;
		
		-s | --size)
			size="$2"; shift 2 ;;
		
		-p | --periods)
			periods="$2"; shift 2 ;;
		
		-v | --verbose)
			verbose="$2"; shift 2 ;;
		
		-a | --async)

			if [ ! -z "$2" ]; then
				async="$2"
			else
				old=$(sudo cat /sys/kernel/debug/dmatest/async_mode)

				if [ "$old" == "Y" ]; then
					async="N"
				else
					async="Y"
				fi
			fi

			shift 2 ;;

		-d | --direction)

			if [ ! -z "$2" ]; then
				dire="$2"
			else
				old=$(sudo cat /sys/kernel/debug/dmatest/direction)
				
				if [ "$old" == "Y" ]; then
					dire="N"
				else
				    dire="Y"
				fi
			fi

			shift 2;;
		
		-b | --batch)

			if [ ! -z "$2" ]; then
				batch="$2"
			else
				old=$(sudo cat /sys/kernel/debug/dmatest/batch_mode)
				
				if [ "$old" == "Y" ]; then
					batch="N"
				else
				    batch="Y"
				fi
			fi

			shift 2 ;;
		
		-m | --mode2d)
			
			if [ ! -z "$2" ]; then
			    mode2d="$2"
			else
				old=$(sudo cat /sys/kernel/debug/dmatest/2d_mode)
				
				if [ "$old" == "Y" ]; then
					mode2d="N"
				else
				    mode2d="Y"
				fi
			fi
			
			shift 2 ;;	 
			
		--) shift 2; break ;;
		*) echo "Error parsing opts ($1,$2) aborting." ; exit 1 ;;
	esac
done

if [ ! -z $value ]; then
   	echo -n "$value" | sudo tee /sys/kernel/debug/dmatest/dvc_value &> /dev/null
fi

if [ ! -z $periods ]; then
	echo -n "$periods" | sudo tee /sys/kernel/debug/dmatest/periods &> /dev/null
fi

if [ ! -z $size ]; then
	echo -n "$size" | sudo tee /sys/kernel/debug/dmatest/glob_size &> /dev/null
fi

if [ ! -z $async ]; then
	echo -n "$async" | sudo tee /sys/kernel/debug/dmatest/async_mode &> /dev/null
fi

if [ ! -z $mode2d ]; then
	echo -n "$mode2d" | sudo tee /sys/kernel/debug/dmatest/2d_mode &> /dev/null
fi

if [ ! -z $verbose ]; then
	echo -n "$verbose" | sudo tee /sys/kernel/debug/dmatest/verbose &> /dev/null
fi

if [ ! -z $batch ]; then
   	echo -n "$batch" | sudo tee /sys/kernel/debug/dmatest/batch_mode &> /dev/null
fi

if [ ! -z $dire ]; then
	echo -n "$dire" | sudo tee /sys/kernel/debug/dmatest/direction &> /dev/null
fi
