#!/bin/bash

value=$(( ( RANDOM % 32 )  + 1 ))
verbose=1
size="4K"
periods=1
async="Y"
mode2d="N"
batch="N"
direction="Y"
def=""

# read the options
TEMP=`getopt -o n:s:p:a::b::v:2::d::o --long value:,size:,periods:,async::,batch::,verbose:,2dmode::,direction::,original -n 'sendpar' -- "$@"`
eval set -- "$TEMP"

while true ; do
    case "$1" in
		-n | --value)
			value="$2" ; shift 2 ;
			echo -n "$value" | sudo tee /sys/kernel/debug/dmatest/dvc_value &> /dev/null ;;

		-s | --size)
			size="$2" ; shift 2 ;
			echo -n "$size" | sudo tee /sys/kernel/debug/dmatest/glob_size &> /dev/null ;;

		-p | --periods)
			periods="$2" ; shift 2 ;
			echo -n "$periods" | sudo tee /sys/kernel/debug/dmatest/periods &> /dev/null ;;
		
		-a | --async)

			if [ ! -z "$2" ]; then
				async="$2"
			else
				old=$(sudo cat /sys/kernel/debug/dmatest/async_mode)

				if [ "$old" == "Y" ]; then
					async="N"
				else
					async="Y"
				fi
			fi
			
			echo -n "$async" | sudo tee /sys/kernel/debug/dmatest/async_mode &> /dev/null
			shift 2;;

		-d | --direction)

			if [ ! -z "$2" ]; then
			    direction="$2"
			else
				old=$(sudo cat /sys/kernel/debug/dmatest/direction)
				
				if [ "$old" == "Y" ]; then
					direction="N"
				else
				    direction="Y"
				fi
			fi
			
			echo -n "$direction" | sudo tee /sys/kernel/debug/dmatest/direction &> /dev/null
			shift 2;;
		
		-b | --batch)

			if [ ! -z "$2" ]; then
				batch="$2"
			else
				old=$(sudo cat /sys/kernel/debug/dmatest/batch_mode)
				
				if [ "$old" == "Y" ]; then
					batch="N"
				else
				    batch="Y"
				fi
			fi
			
			echo -n "$batch" | sudo tee /sys/kernel/debug/dmatest/batch_mode &> /dev/null
			shift 2;;
		
		-2 | --2dmode)
			
			if [ ! -z "$2" ]; then
			    mode2d="$2"
			else
				old=$(sudo cat /sys/kernel/debug/dmatest/2d_mode)
				
				if [ "$old" == "Y" ]; then
					mode2d="N"
				else
				    mode2d="Y"
				fi
			fi
			
			echo -n "$mode2d" | sudo tee /sys/kernel/debug/dmatest/2d_mode &> /dev/null
			shift 2;;

		-v | --verbose)
			verbose="$2" ; shift 2 ;
			echo -n "$verbose" | sudo tee /sys/kernel/debug/dmatest/verbose &> /dev/null ;;

		-o | --original)
			def="Y" ; shift ;;
		
		--) shift ; break ;;
		*) echo "Error parsing opts, aborting." ; exit 1 ;;
	esac
done

if [ ! -z "$def" ]; then

	echo -n "$value" | sudo tee /sys/kernel/debug/dmatest/dvc_value &> /dev/null
	echo -n "$size" | sudo tee /sys/kernel/debug/dmatest/glob_size &> /dev/null
	echo -n "$periods" | sudo tee /sys/kernel/debug/dmatest/periods &> /dev/null
	echo -n "$async" | sudo tee /sys/kernel/debug/dmatest/async_mode &> /dev/null
	echo -n "$mode2d" | sudo tee /sys/kernel/debug/dmatest/2d_mode &> /dev/null
	echo -n "$verbose" | sudo tee /sys/kernel/debug/dmatest/verbose &> /dev/null
	echo -n "$batch" | sudo tee /sys/kernel/debug/dmatest/batch_mode &> /dev/null
	echo -n "$direction" | sudo tee /sys/kernel/debug/dmatest/direction &> /dev/null
	
fi

