#!/bin/bash

if [ ! -c /dev/cryptotest ]; then
	exit 1
fi

while read line; do

	tid=$(echo "$line" | awk -F ":" '{print $1}' | xargs)
	#echo "TID: $tid"

	if [ ! -z $tid ]; then
		./rmtext "$tid"
	fi

done< <(./prtexts | head -n -1)
