#!/bin/bash

mode=9
verbose=1 #Detailed Errors
cmd="2"
if [ ! -c /dev/cryptotest ]; then
	./dotestdev
fi

text_bytes=$(( $(sudo cat /sys/kernel/debug/cryptotest/text | cut -d ' ' -f 1) ))

if [ ! -z $1 ]; then
	mode=$1
fi

#tid
if [ ! -z $2 ]; then
	cmd="$cmd,$2"
fi

#jid
if [ ! -z $3 ]; then
	cmd="$cmd,$3"
fi

case $mode in
	9 | 10);;
	*) echo "Bad mode found ($mode) for CRC, aborting." && exit 1;
esac

if [ $text_bytes -eq 0 ]; then
   ./gentext $(( (RANDOM % 5) + 1))
   cmd="2,0"
fi

sudo dmesg --clear && ./sendpar -v $verbose -m $mode && ./sendcmd "$cmd" && dmesg
