#!/bin/bash

if [ ! -c /dev/cryptotest ]; then
	./dotestdev
fi

if [ ! -z "$1" ]; then
    tid="$1"
else
	echo "Please provide the ID of the text to remove, aborting"
	exit 1;
fi

if [ ! -z "$2" ]; then
	jid="$2"
fi

if [ ! -z "$jid" ]; then
	./sendcmd "6,$tid"
else
	./sendcmd "6,$tid,$jid"
fi
