#!/bin/bash

mode=3
verbose=1 #Detailed Errors

if [ ! -c /dev/cryptotest ]; then
	./dotestdev
fi

text_bytes=$(( $(sudo cat /sys/kernel/debug/cryptotest/text | cut -d ' ' -f 1) ))

if [ ! -z $1 ]; then
	mode=$1
fi

if [ ! -z $2 ]; then
	verbose=$2
fi

case $mode in
	3 | 4) key=8;;
	5 | 6) key=24;;
	*) echo "Bad mode found ($mode) for DES variants, aborting." && exit 1;
esac

if [ $text_bytes -eq 0 ]; then
   ./gentext $(( (RANDOM % 5) + 1))
fi

sudo dmesg --clear && ./sendpar -v $verbose -m $mode -k $key && ./sendcmd 1,2 && dmesg
