#!/bin/bash

if [ ! -c /dev/cryptotest ]; then
	./dotestdev
fi

if [ ! -z "$1" ]; then
    tid="$1"
else
	echo "Please provide the ID of the text to update, aborting"
	exit 1;
fi

if [ ! -z "$2" ]; then
	text="$2"
else
	read -p "Enter the new text: " text	
fi

./sendpar -t "$text"
./sendcmd "5,$tid"
